disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Jozef Juris"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = ""

["params.author"]
headline = """
System Engineer and Infrastructure Architect.

15+ years in the field.

Father.
"""
