[[main]]
none = "none"

[[main]]
name = "Career"
pageRef = "Career"
identifier = "btvjtzPOlj"
weight = 7_777

[[main]]
name = "Education"
pageRef = "Education"
identifier = "FBHVWro6J1"
weight = 8_888

[[footer]]
none = "none"
