[[main]]
none = "none"

[[main]]
name = "Education"
pageRef = "Education"
identifier = "FBHVWro6J1"
weight = 1

[[main]]
name = "Career"
pageRef = "Career"
identifier = "btvjtzPOlj"
weight = 2

[[main]]
name = "Projects"
pageRef = "Projects"
identifier = "wBsj54FCMm"
weight = 3

[[main]]
name = "Contact"
pageRef = "Contact"
identifier = "oNrFfvGeRy"
weight = 4

[[main]]
name = "Blog"
url = "https://www.jozefjuris.sk/"
identifier = "fAc2bgMI2V"
weight = 5

[[footer]]
none = "none"
